image: node:10-alpine

cache:
  paths:
  - node_modules/

stages:
  - get_dependencies
  - test

get_dependencies:
  stage: get_dependencies
  script: yarn

test_translations:
  stage: test
  script: yarn check-translations

test_linter:
  stage: test
  script: yarn lint

test_jest:
  stage: test
  script: 
    - cp src/__mocks__/config.js src/config.js
    - yarn test
